name: Build Debug

on:
  workflow_dispatch:

jobs:
  build_nomaps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get versionCode
        id: versioncode
        run: echo "versionCode=$(grep 'versionCode' app/build.gradle.kts | awk '{ print $3 }' | head -n 1)" >> $GITHUB_OUTPUT
      - name: Get versionName
        id: versionname
        run: echo "versionName=$(grep 'versionName' app/build.gradle.kts | head -1 | awk -F\" '{ print $2 }')" >> $GITHUB_OUTPUT
      - name: Strip internet permission
        run: chmod +x ./strip_permission.sh && ./strip_permission.sh
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          cache: 'gradle'
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Gallery-NoMaps-Debug-${{ steps.versionname.outputs.versionName }}-${{ steps.versioncode.outputs.versionCode }}
          path: app/build/**/*.apk 

  build_maps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get versionCode
        id: versioncode
        run: echo "versionCode=$(grep 'versionCode' app/build.gradle.kts | awk '{ print $3 }' | head -n 1)" >> $GITHUB_OUTPUT
      - name: Get versionName
        id: versionname
        run: echo "versionName=$(grep 'versionName' app/build.gradle.kts | head -1 | awk -F\" '{ print $2 }')" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          cache: 'gradle'
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Load Maps Token
        env:
          MAPS_TOKEN: $
        run: echo MAPS_TOKEN=\"$MAPS_TOKEN\" > ./api.properties
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Gallery-Maps-Debug-${{ steps.versionname.outputs.versionName }}-${{ steps.versioncode.outputs.versionCode }}
          path: app/build/**/*.apk